import requests                         # built-in Python REST support
import logging                          # built-in Python logging

logger = logging.getLogger(__name__)    # set module-level logging object

def planet(cmd:dict[str, list[str]], s:requests.Session) -> str:
    '''
    Entry point for the planet command. Accepts a command dict and returns
    something...I'm not sure what yet.
    
    :param cmd: Command string generated by sfc module.
    :type cmd: dict[str, list[str]]
    :param s: Current REST session object
    :type s: requests.Session
    :return: Unsure about what the return type or description will be yet.
    :rtype: str
    '''

    logger.debug("Entered function planet().")

    opts = parseArgs(cmd["args"])

    return ""

def parseArgs(opts:list[str]) -> list[str]:
    logger.debug("Entered function parseArgs().")
    return []

def displayHelp():
    logger.debug("Entered function displayHelp().")
    pass